[package]
name = "terpy-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "terpy_core"
path = "src/lib.rs"

[dependencies]
prost = "0.11.6"
serde = { version = "1.0.152", features = ["derive"] }
tonic = "0.8.3"

[build-dependencies]
tonic-build = "0.8.3"
