use diesel::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize, Insertable)]
#[diesel(table_name = crate::test_results_t)]
pub struct NewTestResults {
    cbc: f32,
    cbd: f32,
    cbda: f32,
    cbdv: f32,
    cbg: f32,
    cbga: f32,
    cbn: f32,
    d9thc: f32,
    d8thc: f32,
    thcv: f32,
    thca: f32,
    a_bisabolol: f32,
    a_humulene: f32,
    a_pinene: f32,
    a_terpinene: f32,
    b_caryophyllene: f32,
    b_myrcene: f32,
    b_pinene: f32,
    camphene: f32,
    caryophyllene_oxide: f32,
    delta_3_carene: f32,
    gamma_terpinene: f32,
    geraniol: f32,
    guaiol: f32,
    isopulegol: f32,
    linalool: f32,
    trans_nerolidol: f32,
    ocimene: f32,
    p_cymene: f32,
    eucalyptol: f32,
    terpinolene: f32,
}

#[derive(Debug, Deserialize, Serialize, Queryable)]
#[diesel(table_name = crate::test_results_t)]
pub struct TestResults {
    id: String,
    cbc: f32,
    cbd: f32,
    cbda: f32,
    cbdv: f32,
    cbg: f32,
    cbga: f32,
    cbn: f32,
    d9thc: f32,
    d8thc: f32,
    thcv: f32,
    thca: f32,
    a_bisabolol: f32,
    a_humulene: f32,
    a_pinene: f32,
    a_terpinene: f32,
    b_caryophyllene: f32,
    b_myrcene: f32,
    b_pinene: f32,
    camphene: f32,
    caryophyllene_oxide: f32,
    delta_3_carene: f32,
    gamma_terpinene: f32,
    geraniol: f32,
    guaiol: f32,
    isopulegol: f32,
    linalool: f32,
    trans_nerolidol: f32,
    ocimene: f32,
    p_cymene: f32,
    eucalyptol: f32,
    terpinolene: f32,
}
